# Practical 07 : Text Analytics
1. Extract Sample document and apply following document preprocessing methods:
Tokenization, POS Tagging, stop words removal, Stemming and Lemmatization.
2. Create representation of document by calculating Term Frequency and Inverse Document
Frequency.

In [13]:
import nltk
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Atif\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Atif\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Atif\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Atif\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Atif\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [14]:
text = "Tokenization is the process of splitting sentences into words help to study studying studies better and best good computer"

## Part 1 :  Document Preprocessing

### Tokenization

In [15]:
from nltk.tokenize import word_tokenize
tokenize_words = word_tokenize(text)
tokenize_words

['Tokenization',
 'is',
 'the',
 'process',
 'of',
 'splitting',
 'sentences',
 'into',
 'words',
 'help',
 'to',
 'study',
 'studying',
 'studies',
 'better',
 'and',
 'best',
 'good',
 'computer']

### Remove Stopwords

In [16]:
from nltk.corpus import stopwords

In [17]:
sw = set(stopwords.words("english"))
print(sw)

{'by', "you'd", "she'll", 'over', 'and', 'doesn', 'are', 'any', "i'm", 'this', "we'd", 'only', 'what', 't', 'hadn', 'had', 'not', 'further', 'don', "they'll", 'from', 'been', "we'll", 'where', 'who', 'whom', 'these', 'how', 'above', 'there', 'wouldn', "hadn't", 'her', 'those', 'you', "i'll", 'my', "isn't", 'through', "we're", 'ma', 'aren', 'your', 'himself', 'couldn', 'an', "doesn't", 'until', 'yourself', 'or', 'didn', 'same', 'him', 'but', 'few', 'ourselves', 'such', 'hers', 'am', 'own', 's', 'have', 'yours', 'in', 'be', 'is', "i've", 'll', 'can', "wouldn't", 'me', 'won', 'yourselves', "you'll", 've', 'all', 'because', 'very', 'while', "you're", 'haven', 'ain', 'mightn', 'do', 'about', 'themselves', 'his', 'wasn', 'both', 'when', 'below', 'its', "shan't", "she'd", 'than', 'the', 'isn', "didn't", "it'd", 'theirs', "they're", 'other', "wasn't", 'were', 'a', "he'd", 'before', 'shan', 'herself', "aren't", 'under', "they'd", "you've", 'she', 'having', 'needn', 'weren', 'once', 'we', 'will', 'again', "mightn't", "it's", 'up', 'just', 'now', 'for', 'out', 'should', 'itself', "don't", 'if', 'as', 'of', 'to', 'some', "needn't", 'so', 'into', 'd', 'too', 'o', 'being', 'down', 'ours', 'was', 'hasn', 'they', 'y', 'between', 'doing', 'each', "haven't", 'that', "mustn't", 'm', 're', 'shouldn', 'myself', "he'll", "that'll", "we've", 'which', "won't", 'during', 'most', 'then', 'mustn', "weren't", 'here', 'no', 'at', 'it', 'he', 'does', "i'd", "hasn't", 'their', "it'll", 'i', 'off', 'against', 'after', "she's", 'more', 'them', 'nor', "he's", 'with', 'on', 'did', "shouldn't", 'has', 'our', "should've", 'why', "couldn't", "they've"}

In [18]:
filtered_words = []
for word in tokenize_words:
    if word.lower() not in sw:
        filtered_words.append(word)

filtered_words

['Tokenization',
 'process',
 'splitting',
 'sentences',
 'words',
 'help',
 'study',
 'studying',
 'studies',
 'better',
 'best',
 'good',
 'computer']

### Regular Expression

In [19]:
import re
text1 = "How to remove Stopword,punctuation from nltk library in pyhton ? "

text2 = re.sub('[^a-zA-z]',' ',text1)

In [20]:
text2

'How to remove Stopword punctuation from nltk library in pyhton   '

### POS Tagging

In [21]:
from nltk import pos_tag
print(pos_tag(filtered_words),"\n")

[('Tokenization', 'NN'), ('process', 'NN'), ('splitting', 'VBG'), ('sentences', 'NNS'), ('words', 'NNS'), ('help', 'VBP'), ('study', 'VB'), ('studying', 'VBG'), ('studies', 'NNS'), ('better', 'RBR'), ('best', 'RB'), ('good', 'JJ'), ('computer', 'NN')]

### Stemming

In [22]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
for word in filtered_words:
    print(ps.stem(word),end = ' ')

token process split sentenc word help studi studi studi better best good comput

### Lemmatization

In [23]:
from nltk.stem import WordNetLemmatizer
le = WordNetLemmatizer()
for w in filtered_words:
    print(w, " : ",le.lemmatize(w))

Tokenization  :  Tokenization
process  :  process
splitting  :  splitting
sentences  :  sentence
words  :  word
help  :  help
study  :  study
studying  :  studying
studies  :  study
better  :  better
best  :  best
good  :  good
computer  :  computer

## Part 2 : Text Representation

### Term Frequency(TF)

In [52]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer


clean_doc = ["Data is very is big data very very"]

vect = CountVectorizer()
X = vect.fit_transform(clean_doc)

words = vect.get_feature_names_out()
counts = X.toarray()[0]

df1 = pd.DataFrame({
    "Word": words,
    "TF-IDF": counts
})
df1

   Word  TF-IDF
0   big       1
1  data       2
2    is       2
3  very       3

### Inverse Document Frequency

In [53]:

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(clean_doc)

words = tfidf.get_feature_names_out()
values = X_tfidf.toarray()[0]

# Create DataFrame
df = pd.DataFrame({
    "Word": words,
    "TF-IDF": values
})

df

   Word    TF-IDF
0   big  0.235702
1  data  0.471405
2    is  0.471405
3  very  0.707107

In [55]:
documentA="Jupyter is the largest planet"
documentB="Mars is the 4th planet from the sun"

## Bag of words 
bagOfWordsA= documentA.split(' ')
bagOfWordsB= documentB.split(' ')

## Create collection of unique search
uniqueWords = set(bagOfWordsA).union(bagOfWordsB)
uniqueWords

{'4th', 'Jupyter', 'Mars', 'from', 'is', 'largest', 'planet', 'sun', 'the'}

In [63]:
## Unique documents from the document A
numsOfWords1 = dict.fromkeys(uniqueWords,0)
for word in bagOfWordsA:
    numsOfWords1[word]+=1
numsOfWords1

{'from': 0,
 'Jupyter': 1,
 'Mars': 0,
 'planet': 1,
 'sun': 0,
 'is': 1,
 'the': 1,
 'largest': 1,
 '4th': 0}

In [64]:
## Unique documents from the document B
numsOfWords2 = dict.fromkeys(uniqueWords,0)
for word in bagOfWordsB:
    numsOfWords2[word]+=1
numsOfWords2

{'from': 1,
 'Jupyter': 0,
 'Mars': 1,
 'planet': 1,
 'sun': 1,
 'is': 1,
 'the': 2,
 'largest': 0,
 '4th': 1}

In [66]:
def computeTF(wordDict,bagOfWords):
    TFDict ={}
    bagcount = len(bagOfWords)
    for word,count in wordDict.items():
        TFDict[word] = count/float(bagcount)
    return TFDict

In [69]:
TFA = computeTF(numsOfWords1, bagOfWordsA)

In [70]:
TFA

{'from': 0.0,
 'Jupyter': 0.2,
 'Mars': 0.0,
 'planet': 0.2,
 'sun': 0.0,
 'is': 0.2,
 'the': 0.2,
 'largest': 0.2,
 '4th': 0.0}

In [71]:
TFB= computeTF(numsOfWords2, bagOfWordsB)
TFB

{'from': 0.125,
 'Jupyter': 0.0,
 'Mars': 0.125,
 'planet': 0.125,
 'sun': 0.125,
 'is': 0.125,
 'the': 0.25,
 'largest': 0.0,
 '4th': 0.125}